## numpy - numeric python
## pandas
## matplot lib

In [2]:
import numpy as np # complete package
#from numpy inport array (only individual level)

**one dimensional array**

In [11]:
a=np.array([2,3,4,5]) # changing the list into array using numpy
print(a)
type(a)

[2 3 4 5]


numpy.ndarray

**two dimensional array**

In [59]:
a=np.array([[2,3,4,5]]) 
b=np.array([[1,2,3],[5,6,7],[8,9,6]])
print(a.ndim)  # to check the dimension of the array
print(b.ndim)
print(a.dtype)
type(a)

2
2
int32


numpy.ndarray

In [9]:
print(a)
print(b)

[[2 3 4 5]]
[[1 2 3]
 [5 6 7]
 [8 9 6]]


**three dimensional array**

In [27]:
c=np.array([[[1,2,3],[3,4,5]]])
print(c.ndim)
print(c)
type(c)

3
[[[1 2 3]
  [3 4 5]]]


numpy.ndarray

In [18]:
print(b.shape)  # number of rows and columns
print(b.size)  # number of elements
print(b.itemsize) # memory occupied by each element

(3, 3)
9
4


In [19]:
print(a.shape)  # number of rows and columns
print(a.size)  # number of elements
print(a.itemsize) # memory occupied by each element

(1, 4)
4
4


In [20]:
print(c.shape)  # number of sets, rows and columns
print(c.size)  # number of elements
print(c.itemsize) # memory occupied by each element

(1, 3, 3)
9
4


In [46]:
d=np.array([[[1,2,3]],[[3,4,5]],[[2,3,4]]])
print(d.shape)
print(d)


(3, 1, 3)
[[[1 2 3]]

 [[3 4 5]]

 [[2 3 4]]]


#### methods to create array
- range

- arange

- linspace

In [31]:
np.array(range(1,10))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.array(range(1,10,3))

array([1, 4, 7])

In [36]:
p=np.array(range(10,1,-2))
print(p)

[10  8  6  4  2]


In [38]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

**range and arange are same methods but range uses array keyword and arange don't**

**equal distribution formula==(end-1)/(size-1)**
- includes the ending element also <br>
- third number specifies the size<br>
- and it prints in equal distribution

In [47]:
np.linspace(1,10,5) 

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [49]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [62]:
q=np.zeros((1,2),dtype=int)
q.dtype

dtype('int32')

In [63]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [64]:
np.full((3,3),5.6)

array([[5.6, 5.6, 5.6],
       [5.6, 5.6, 5.6],
       [5.6, 5.6, 5.6]])

### random array creation
- random.randint

- random.randn

- random.random

- random.rand

In [70]:
print(np.random.randint(5,10))
np.random.randint(1,100,(2,3))

6


array([[59, 97, 68],
       [59, 74, 61]])

In [72]:
np.random.randn(2,3) #both positive and negative... we cant specify the range

array([[-0.33267499, -1.61438457, -0.99690659],
       [ 0.26151975, -2.34970237,  0.7706035 ]])

In [75]:
print(np.random.random((2,3))) # it takes only one argument

[[0.22863531 0.04501522 0.1939656 ]
 [0.58777316 0.05275016 0.21793175]]


In [74]:
print(np.random.rand(2,3))

[[0.62863754 0.91062514 0.81836171]
 [0.1682778  0.91872622 0.26575421]]


In [76]:
a=np.random.randint(1,100,(8,7))

In [77]:
a

array([[83, 29, 64, 96,  3, 10, 73],
       [18,  1, 12, 25, 66, 50, 27],
       [36, 22, 31, 44, 48, 20, 10],
       [ 7, 18, 25, 60, 46,  1, 41],
       [45,  8, 65, 75, 59, 84, 48],
       [18, 39, 39, 30,  7, 22, 14],
       [86, 18,  4, 17, 68, 15, 64],
       [23, 27, 28, 62, 42, 26, 91]])

In [79]:
a[2:4] #since it has no comma it is specifying only rows

array([[36, 22, 31, 44, 48, 20, 10],
       [ 7, 18, 25, 60, 46,  1, 41]])

In [80]:
a[2:5,1:5]

array([[22, 31, 44, 48],
       [18, 25, 60, 46],
       [ 8, 65, 75, 59]])

In [81]:
a[2:5:2,1:5:2] # 2,4 rows   1,3 columns

array([[22, 44],
       [ 8, 75]])

In [90]:
r=np.arange(1,21)
print(r)
r.reshape(5,4)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [91]:
np.mean(r)

10.5

In [92]:
np.median(r)

10.5

In [93]:
np.std(r)

5.766281297335398

In [97]:
print(np.quantile(r,0.25))
print(np.quantile(r,0.5))
print(np.quantile(r,0.75))

5.75
10.5
15.25


In [96]:
r


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

### array stacking

- horizontal stack (hstack)       (no of rows should be equal)
- vertical stack (vstack)        (no of columns should be equal)

In [104]:
a=np.array([[1,2,3],[3,4,5]])
b=np.array([[6,7,8,8],[5,4,3,9]])
print(a)
print(b)

[[1 2 3]
 [3 4 5]]
[[6 7 8 8]
 [5 4 3 9]]


In [105]:
np.hstack((b,a))

array([[6, 7, 8, 8, 1, 2, 3],
       [5, 4, 3, 9, 3, 4, 5]])

In [106]:
np.vstack((b,a))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 4 and the array at index 1 has size 3

In [107]:
a.shape

(2, 3)

In [109]:
import math
print(math.log(2))
math.log(3)

0.6931471805599453


1.0986122886681098

# pandas

In [111]:
import pandas as pd
import numpy as np

AttributeError: partially initialized module 'pandas' has no attribute 'core' (most likely due to a circular import)